language: php

os: linux
dist: xenial

php:
  - 7.4
  - 8.0
  - 8.1
  - hhvm

jobs:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-source --no-interaction --dev

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction

script:
  - ./vendor/bin/phpunit

notifications:
  email:
    on_success: always
    on_failure: always
